"use client";

import NuraPageShell from "@/components/NuraPageShell";

const TEXT = "#f0ebde";
const TEXT_BODY = "rgba(235,230,216,0.85)";
const TEXT_SEC = "rgba(235,230,216,0.55)";
const SAGE = "#9bb0a5";
const RED = "#d4574d";
const SANS = "'Inter', system-ui, sans-serif";
const SERIF = "'DM Serif Display', Georgia, serif";

type Block =
  | { type: "p"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "emergency"; lead: string; body: string };

type Section = { title: string; blocks: Block[] };

const INTRO =
  "NŪRA is a general wellness platform designed to provide educational information and personalized guidance for healthy lifestyle goals. The Service is not a substitute for professional medical care. Please read this disclaimer carefully and consult a qualified healthcare provider before making decisions about your health.";

const SECTIONS: Section[] = [
  {
    title: "1. Not Medical Advice",
    blocks: [
      {
        type: "p",
        text: "All content, AI-generated responses, bloodwork analyses, supplement recommendations, wellness protocols, and other information provided through NŪRA are for general wellness, educational, and informational purposes only. They are NOT medical advice, diagnosis, treatment, or prescription. NŪRA is not a licensed healthcare provider, medical practice, or telehealth service. No content on the Service should be interpreted as a recommendation to take or stop any medication, supplement, treatment, or therapy without first consulting a qualified healthcare provider.",
      },
    ],
  },
  {
    title: "2. Consult Your Healthcare Provider",
    blocks: [
      {
        type: "p",
        text: "Always seek the advice of your physician, naturopathic doctor, registered dietitian, or other qualified healthcare provider with any questions you may have regarding a medical condition, medication, supplement, or health-related decision. Never disregard professional medical advice or delay in seeking it because of something you have read or learned on NŪRA. Information from NŪRA should be used to inform conversations with your healthcare provider, not replace them.",
      },
    ],
  },
  {
    title: "3. Emergency Situations",
    blocks: [
      {
        type: "emergency",
        lead: "NŪRA is not intended for emergency use. If you are experiencing a medical emergency, call 911 (or your local emergency number) immediately.",
        body: "Do not use NŪRA to seek help in life-threatening situations. Signs of medical emergency include but are not limited to: chest pain, difficulty breathing, severe bleeding, stroke symptoms, severe allergic reactions, suicidal thoughts, or any other condition you reasonably believe to be life-threatening.",
      },
    ],
  },
  {
    title: "4. AI-Generated Content Limitations",
    blocks: [
      {
        type: "p",
        text: "Responses generated by NŪRA's AI may contain inaccuracies, omissions, or outdated information. AI-generated content is based on patterns in training data and the information you provide; it is not the considered judgment of a healthcare professional who knows you, your medical history, and your specific circumstances. Always verify health-related information with qualified professionals before acting on it.",
      },
    ],
  },
  {
    title: "5. Bloodwork Analysis Disclaimer",
    blocks: [
      {
        type: "p",
        text: "NŪRA may help you interpret bloodwork results in the context of general wellness ranges and offer educational insights. This is not a diagnostic service. NŪRA cannot detect all abnormalities, cannot replace a comprehensive medical evaluation, and cannot account for your full clinical picture, family history, physical examination, or other tests. Discuss all bloodwork results with your healthcare provider.",
      },
    ],
  },
  {
    title: "6. Supplement and Herbal Medicine Guidance",
    blocks: [
      {
        type: "p",
        text: "NŪRA may suggest supplements, herbs, vitamins, minerals, or other natural products as part of general wellness protocols. These suggestions are educational and not prescriptions. Important considerations:",
      },
      {
        type: "ul",
        items: [
          "Supplements and herbs can interact with medications, other supplements, and medical conditions.",
          "Dosages effective for some individuals may be inappropriate or harmful for others.",
          "Pregnancy, breastfeeding, scheduled surgery, chronic conditions, and certain medications create additional risks.",
          "Quality, purity, and potency of supplements vary by manufacturer.",
          "The U.S. Food and Drug Administration has not evaluated most supplement health claims.",
        ],
      },
      {
        type: "p",
        text: "Consult a qualified healthcare provider, pharmacist, or licensed herbalist before starting any new supplement, especially if you are taking medications, have a medical condition, are pregnant or nursing, or are preparing for surgery.",
      },
    ],
  },
  {
    title: "7. Individual Variation",
    blocks: [
      {
        type: "p",
        text: "Health responses are highly individual. What works well for one person may not work for another, and may even be harmful. Genetic factors, existing conditions, medications, lifestyle, and many other variables affect how your body responds to any intervention. NŪRA's recommendations are general guidance, not personalized prescriptions, and should be adapted to your individual circumstances under professional supervision.",
      },
    ],
  },
  {
    title: "8. No Doctor-Patient Relationship",
    blocks: [
      {
        type: "p",
        text: "Use of NŪRA does not create a doctor-patient, therapist-client, or any other professional healthcare relationship between you and NŪRA, its operators, contributors, or employees. NŪRA does not provide ongoing medical care, follow-up, or monitoring.",
      },
    ],
  },
  {
    title: "9. Pregnancy, Nursing, and Vulnerable Populations",
    blocks: [
      {
        type: "p",
        text: "If you are pregnant, breastfeeding, trying to conceive, under the age of 18, over the age of 65, or have a serious medical condition, you should consult a qualified healthcare provider before acting on any information from NŪRA. Many wellness protocols, supplements, and herbs are contraindicated in these populations.",
      },
    ],
  },
  {
    title: "10. Mental Health",
    blocks: [
      {
        type: "p",
        text: "NŪRA is not a mental health service. If you are experiencing depression, anxiety, suicidal thoughts, addiction, or other mental health concerns, please contact a qualified mental health professional or call 988 (Suicide and Crisis Lifeline) in the United States. NŪRA cannot replace the support of a trained therapist, counselor, or psychiatrist.",
      },
    ],
  },
  {
    title: "11. Reliance",
    blocks: [
      {
        type: "p",
        text: "Your reliance on any information provided by NŪRA is solely at your own risk. NŪRA, its operators, and contributors disclaim all liability for actions you take or fail to take based on information from the Service. You assume full responsibility for any consequences of decisions made using NŪRA.",
      },
    ],
  },
  {
    title: "12. Acknowledgment",
    blocks: [
      {
        type: "p",
        text: "By using NŪRA, you acknowledge that you have read, understood, and agree to this Medical Disclaimer. If you do not agree, please discontinue use of the Service immediately.",
      },
    ],
  },
  {
    title: "Contact",
    blocks: [
      {
        type: "p",
        text: "Questions about this disclaimer can be directed to [EMAIL].",
      },
    ],
  },
];

export default function MedicalDisclaimerPage() {
  return (
    <NuraPageShell maxWidth={760}>
      <h1
        style={{
          fontFamily: SERIF,
          fontWeight: 500,
          color: TEXT,
          margin: "0 0 6px",
          lineHeight: 1.15,
          letterSpacing: "-0.5px",
          fontSize: "clamp(32px, 5vw, 44px)",
        }}
      >
        Medical Disclaimer
      </h1>
      <p style={{ fontFamily: SANS, fontSize: 13, color: TEXT_SEC, margin: "0 0 28px" }}>
        Last updated: May 14, 2026
      </p>

      <p style={bodyStyle()}>{INTRO}</p>

      {SECTIONS.map((s) => (
        <Section key={s.title} title={s.title} blocks={s.blocks} />
      ))}
    </NuraPageShell>
  );
}

function Section({ title, blocks }: { title: string; blocks: Block[] }) {
  return (
    <>
      <h2 style={headingStyle()}>{title}</h2>
      {blocks.map((b, i) => {
        if (b.type === "p") {
          return (
            <p key={i} style={bodyStyle(i > 0 ? 10 : 0)}>
              {renderInline(b.text)}
            </p>
          );
        }
        if (b.type === "ul") {
          return (
            <ul key={i} style={{ margin: "10px 0 0", paddingLeft: 22 }}>
              {b.items.map((item, j) => (
                <li
                  key={j}
                  style={{
                    fontFamily: SANS,
                    fontSize: 14,
                    lineHeight: 1.7,
                    color: TEXT_BODY,
                    margin: "0 0 6px",
                  }}
                >
                  {renderInline(item)}
                </li>
              ))}
            </ul>
          );
        }
        return (
          <div
            key={i}
            style={{
              background: "rgba(212,87,77,0.08)",
              border: `1px solid rgba(212,87,77,0.4)`,
              borderLeft: `3px solid ${RED}`,
              borderRadius: 12,
              padding: "16px 18px",
              marginTop: 4,
            }}
          >
            <p
              style={{
                fontFamily: SANS,
                fontSize: 15,
                fontWeight: 600,
                color: RED,
                margin: "0 0 8px",
                letterSpacing: "0.1px",
                lineHeight: 1.5,
              }}
            >
              {b.lead}
            </p>
            <p
              style={{
                fontFamily: SANS,
                fontSize: 14,
                lineHeight: 1.7,
                color: TEXT_BODY,
                margin: 0,
              }}
            >
              {b.body}
            </p>
          </div>
        );
      })}
    </>
  );
}

function headingStyle(): React.CSSProperties {
  return {
    fontFamily: SANS,
    fontSize: 22,
    fontWeight: 500,
    color: SAGE,
    margin: "28px 0 12px",
    letterSpacing: "1px",
    textTransform: "uppercase",
  };
}

function bodyStyle(topMargin = 0): React.CSSProperties {
  return {
    fontFamily: SANS,
    fontSize: 14,
    lineHeight: 1.7,
    color: TEXT_BODY,
    margin: `${topMargin}px 0 0`,
  };
}

function renderInline(text: string): React.ReactNode {
  const parts: React.ReactNode[] = [];
  const regex = /\*\*([^*]+)\*\*/g;
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  let key = 0;
  while ((match = regex.exec(text)) !== null) {
    if (match.index > lastIndex) parts.push(text.slice(lastIndex, match.index));
    parts.push(
      <strong key={key++} style={{ color: SAGE, fontWeight: 500 }}>
        {match[1]}
      </strong>
    );
    lastIndex = regex.lastIndex;
  }
  if (lastIndex < text.length) parts.push(text.slice(lastIndex));
  return parts;
}
