-- Pre-seeded pantry: a broad base of common whole-food ingredients so recipe
-- authoring (and the photo-scan matcher) usually finds an existing match.
--
-- Rules honored here:
--   • status = 'draft' for every seeded row (no deep-dive content yet — these
--     get enriched over time on each ingredient's own admin page).
--   • is_organic left at the column default (false).
--   • name + slug + a one-line tagline only.
--   • IDEMPOTENT: on conflict (slug) do nothing — safe to re-run.
--   • Does NOT touch the existing fully-built ingredients (turmeric, olive-oil,
--     wild-salmon, spinach, garlic, ginger, black-pepper, coconut-milk,
--     red-lentils, wild-blueberries) — their slugs simply conflict and are skipped.

-- The category CHECK only allowed 7 buckets; whole-food seeding needs grains and
-- pantry staples too. Widen it to the final 9-category list (superset — every
-- prior value still valid). "greens" is the vegetables bucket.
alter table public.ingredients drop constraint if exists ingredients_category_check;
alter table public.ingredients
  add constraint ingredients_category_check
  check (category in ('root-spice','greens','legumes','good-fats','ferments','protein','fruit','grains','staple'));

insert into public.ingredients (slug, name, category, tagline, status) values
  -- ── Proteins ────────────────────────────────────────────────────────────
  ('salmon','Salmon','protein','Omega-3 rich oily fish.','draft'),
  ('canned-salmon','Canned Salmon','protein','Convenient omega-3 protein with edible bones for calcium.','draft'),
  ('tuna','Tuna','protein','Lean high-protein fish.','draft'),
  ('canned-tuna','Canned Tuna','protein','Shelf-stable lean protein.','draft'),
  ('sardines','Sardines','protein','Small oily fish loaded with omega-3s and calcium.','draft'),
  ('mackerel','Mackerel','protein','Oily fish high in omega-3s.','draft'),
  ('cod','Cod','protein','Mild flaky white fish.','draft'),
  ('halibut','Halibut','protein','Lean firm white fish.','draft'),
  ('trout','Trout','protein','Freshwater oily fish rich in omega-3s.','draft'),
  ('shrimp','Shrimp','protein','Lean quick-cooking shellfish.','draft'),
  ('scallops','Scallops','protein','Delicate lean shellfish.','draft'),
  ('chicken-breast','Chicken Breast','protein','Lean white-meat poultry.','draft'),
  ('chicken-thigh','Chicken Thigh','protein','Juicy dark-meat poultry.','draft'),
  ('whole-chicken','Whole Chicken','protein','Versatile roasting bird.','draft'),
  ('turkey-breast','Turkey Breast','protein','Very lean poultry.','draft'),
  ('ground-turkey','Ground Turkey','protein','Lean minced poultry.','draft'),
  ('ground-beef','Ground Beef','protein','Versatile minced red meat.','draft'),
  ('beef-steak','Beef Steak','protein','Iron-rich red meat.','draft'),
  ('beef-chuck','Beef Chuck','protein','Marbled cut for slow braising.','draft'),
  ('lamb','Lamb','protein','Iron-rich red meat.','draft'),
  ('pork-tenderloin','Pork Tenderloin','protein','Lean cut of pork.','draft'),
  ('bacon','Bacon','protein','Cured pork for savory depth.','draft'),
  ('eggs','Eggs','protein','Complete protein with choline.','draft'),
  ('tofu','Tofu','protein','Soy-based plant protein.','draft'),
  ('tempeh','Tempeh','protein','Fermented soy protein with a nutty bite.','draft'),
  ('edamame','Edamame','protein','Young green soybeans.','draft'),
  -- ── Greens & vegetables ─────────────────────────────────────────────────
  ('kale','Kale','greens','Sturdy cruciferous leafy green.','draft'),
  ('swiss-chard','Swiss Chard','greens','Mineral-rich leafy green.','draft'),
  ('collard-greens','Collard Greens','greens','Hearty cruciferous green.','draft'),
  ('arugula','Arugula','greens','Peppery salad green.','draft'),
  ('romaine-lettuce','Romaine Lettuce','greens','Crisp salad green.','draft'),
  ('mixed-greens','Mixed Greens','greens','Tender salad leaf blend.','draft'),
  ('watercress','Watercress','greens','Peppery nutrient-dense green.','draft'),
  ('broccoli','Broccoli','greens','Cruciferous vegetable high in sulforaphane.','draft'),
  ('broccoli-rabe','Broccoli Rabe','greens','Bitter cruciferous green.','draft'),
  ('cauliflower','Cauliflower','greens','Versatile cruciferous vegetable.','draft'),
  ('brussels-sprouts','Brussels Sprouts','greens','Mini cruciferous cabbages.','draft'),
  ('cabbage','Cabbage','greens','Crunchy cruciferous vegetable.','draft'),
  ('red-cabbage','Red Cabbage','greens','Anthocyanin-rich cruciferous vegetable.','draft'),
  ('bok-choy','Bok Choy','greens','Mild Asian cabbage.','draft'),
  ('asparagus','Asparagus','greens','Spring spear vegetable.','draft'),
  ('green-beans','Green Beans','greens','Crisp pod vegetable.','draft'),
  ('snap-peas','Snap Peas','greens','Sweet edible-pod peas.','draft'),
  ('peas','Peas','greens','Sweet green pod vegetable.','draft'),
  ('carrots','Carrots','greens','Beta-carotene rich root.','draft'),
  ('beets','Beets','greens','Earthy nitrate-rich root.','draft'),
  ('radish','Radish','greens','Peppery crunchy root.','draft'),
  ('turnip','Turnip','greens','Mild cruciferous root.','draft'),
  ('parsnip','Parsnip','greens','Sweet earthy root.','draft'),
  ('celery','Celery','greens','Crisp hydrating stalk.','draft'),
  ('cucumber','Cucumber','greens','Cooling hydrating vegetable.','draft'),
  ('zucchini','Zucchini','greens','Tender summer squash.','draft'),
  ('yellow-squash','Yellow Squash','greens','Mild summer squash.','draft'),
  ('butternut-squash','Butternut Squash','greens','Sweet winter squash.','draft'),
  ('acorn-squash','Acorn Squash','greens','Nutty winter squash.','draft'),
  ('pumpkin','Pumpkin','greens','Beta-carotene rich winter squash.','draft'),
  ('sweet-potato','Sweet Potato','greens','Fiber-rich orange tuber.','draft'),
  ('potato','Potato','greens','Starchy versatile tuber.','draft'),
  ('tomato','Tomato','greens','Lycopene-rich fruit-vegetable.','draft'),
  ('cherry-tomatoes','Cherry Tomatoes','greens','Sweet bite-size tomatoes.','draft'),
  ('red-bell-pepper','Red Bell Pepper','greens','Vitamin-C rich sweet pepper.','draft'),
  ('green-bell-pepper','Green Bell Pepper','greens','Crisp mild pepper.','draft'),
  ('jalapeno','Jalapeno','greens','Mild-to-medium chili pepper.','draft'),
  ('eggplant','Eggplant','greens','Silky nightshade vegetable.','draft'),
  ('mushrooms','Mushrooms','greens','Umami-rich edible fungi.','draft'),
  ('cremini-mushrooms','Cremini Mushrooms','greens','Earthy brown mushrooms.','draft'),
  ('shiitake-mushrooms','Shiitake Mushrooms','greens','Umami-rich medicinal mushroom.','draft'),
  ('onion','Onion','greens','Aromatic allium base.','draft'),
  ('red-onion','Red Onion','greens','Sharp colorful allium.','draft'),
  ('shallot','Shallot','greens','Mild delicate allium.','draft'),
  ('leek','Leek','greens','Sweet mild allium.','draft'),
  ('scallion','Scallion','greens','Fresh green onion.','draft'),
  ('fennel','Fennel','greens','Anise-scented bulb.','draft'),
  ('artichoke','Artichoke','greens','Fiber-rich thistle bud.','draft'),
  ('okra','Okra','greens','Fiber-rich pod vegetable.','draft'),
  ('corn','Corn','greens','Sweet starchy kernels.','draft'),
  ('endive','Endive','greens','Crisp slightly bitter chicory.','draft'),
  -- ── Legumes ─────────────────────────────────────────────────────────────
  ('green-lentils','Green Lentils','legumes','Hearty protein-rich pulse that holds its shape.','draft'),
  ('brown-lentils','Brown Lentils','legumes','Everyday earthy lentil.','draft'),
  ('black-lentils','Black Lentils','legumes','Firm caviar-like lentil.','draft'),
  ('chickpeas','Chickpeas','legumes','Versatile fiber-rich pulse.','draft'),
  ('black-beans','Black Beans','legumes','Antioxidant-rich creamy bean.','draft'),
  ('kidney-beans','Kidney Beans','legumes','Hearty protein-rich bean.','draft'),
  ('white-beans','White Beans','legumes','Creamy mild bean.','draft'),
  ('cannellini-beans','Cannellini Beans','legumes','Large creamy white bean.','draft'),
  ('pinto-beans','Pinto Beans','legumes','Earthy soft bean.','draft'),
  ('navy-beans','Navy Beans','legumes','Small creamy white bean.','draft'),
  ('split-peas','Split Peas','legumes','Fiber-rich pulse for soups.','draft'),
  ('mung-beans','Mung Beans','legumes','Quick-cooking small bean.','draft'),
  ('fava-beans','Fava Beans','legumes','Buttery spring bean.','draft'),
  ('lima-beans','Lima Beans','legumes','Starchy buttery bean.','draft'),
  -- ── Grains ──────────────────────────────────────────────────────────────
  ('rolled-oats','Rolled Oats','grains','Beta-glucan rich whole grain.','draft'),
  ('steel-cut-oats','Steel-Cut Oats','grains','Chewy minimally processed oats.','draft'),
  ('quinoa','Quinoa','grains','Complete-protein seed grain.','draft'),
  ('brown-rice','Brown Rice','grains','Fiber-rich whole grain rice.','draft'),
  ('white-rice','White Rice','grains','Everyday polished rice.','draft'),
  ('wild-rice','Wild Rice','grains','Nutty protein-rich grass seed.','draft'),
  ('barley','Barley','grains','Chewy beta-glucan rich grain.','draft'),
  ('buckwheat','Buckwheat','grains','Gluten-free nutty pseudo-grain.','draft'),
  ('farro','Farro','grains','Chewy ancient wheat grain.','draft'),
  ('millet','Millet','grains','Mild gluten-free grain.','draft'),
  ('bulgur','Bulgur','grains','Quick-cooking cracked wheat.','draft'),
  ('couscous','Couscous','grains','Tiny steamed wheat pasta.','draft'),
  ('amaranth','Amaranth','grains','Protein-rich tiny pseudo-grain.','draft'),
  ('teff','Teff','grains','Mineral-rich tiny grain.','draft'),
  ('whole-wheat-pasta','Whole Wheat Pasta','grains','Fiber-rich pasta.','draft'),
  ('brown-rice-pasta','Brown Rice Pasta','grains','Gluten-free pasta.','draft'),
  ('sourdough-bread','Sourdough Bread','grains','Naturally leavened bread.','draft'),
  ('whole-grain-bread','Whole Grain Bread','grains','Fiber-rich sandwich bread.','draft'),
  ('corn-tortilla','Corn Tortilla','grains','Gluten-free masa flatbread.','draft'),
  ('polenta','Polenta','grains','Creamy cornmeal porridge.','draft'),
  -- ── Good fats (oils, nuts, seeds) ───────────────────────────────────────
  ('avocado','Avocado','good-fats','Monounsaturated-fat fruit.','draft'),
  ('avocado-oil','Avocado Oil','good-fats','High-smoke-point cooking oil.','draft'),
  ('coconut-oil','Coconut Oil','good-fats','Saturated fat with MCTs.','draft'),
  ('tahini','Tahini','good-fats','Sesame seed paste rich in minerals.','draft'),
  ('almonds','Almonds','good-fats','Vitamin-E rich tree nut.','draft'),
  ('walnuts','Walnuts','good-fats','Omega-3 rich tree nut.','draft'),
  ('pecans','Pecans','good-fats','Buttery antioxidant-rich nut.','draft'),
  ('cashews','Cashews','good-fats','Creamy mild tree nut.','draft'),
  ('pistachios','Pistachios','good-fats','Protein-rich green nut.','draft'),
  ('hazelnuts','Hazelnuts','good-fats','Sweet aromatic nut.','draft'),
  ('macadamia-nuts','Macadamia Nuts','good-fats','Rich buttery nut.','draft'),
  ('brazil-nuts','Brazil Nuts','good-fats','Selenium-dense nut.','draft'),
  ('pine-nuts','Pine Nuts','good-fats','Delicate buttery seed.','draft'),
  ('peanuts','Peanuts','good-fats','Protein-rich legume nut.','draft'),
  ('almond-butter','Almond Butter','good-fats','Creamy vitamin-E rich spread.','draft'),
  ('peanut-butter','Peanut Butter','good-fats','Protein-rich nut spread.','draft'),
  ('pumpkin-seeds','Pumpkin Seeds','good-fats','Magnesium-rich seed.','draft'),
  ('sunflower-seeds','Sunflower Seeds','good-fats','Vitamin-E rich seed.','draft'),
  ('sesame-seeds','Sesame Seeds','good-fats','Calcium-rich tiny seed.','draft'),
  ('chia-seeds','Chia Seeds','good-fats','Omega-3 and fiber rich seed.','draft'),
  ('flax-seeds','Flax Seeds','good-fats','Lignan and omega-3 rich seed.','draft'),
  ('hemp-seeds','Hemp Seeds','good-fats','Complete-protein omega seed.','draft'),
  ('ghee','Ghee','good-fats','Clarified butter with a high smoke point.','draft'),
  ('grass-fed-butter','Grass-Fed Butter','good-fats','Fat-soluble-vitamin rich butter.','draft'),
  ('olives','Olives','good-fats','Briny monounsaturated-fat fruit.','draft'),
  ('dark-chocolate','Dark Chocolate','good-fats','Flavanol-rich cacao treat.','draft'),
  ('coconut-flakes','Coconut Flakes','good-fats','Fiber-rich dried coconut.','draft'),
  -- ── Roots & spices (herbs & spices) ─────────────────────────────────────
  ('cumin','Cumin','root-spice','Warm earthy seed spice.','draft'),
  ('coriander','Coriander','root-spice','Citrusy seed spice.','draft'),
  ('paprika','Paprika','root-spice','Sweet ground pepper spice.','draft'),
  ('smoked-paprika','Smoked Paprika','root-spice','Smoky ground pepper spice.','draft'),
  ('cinnamon','Cinnamon','root-spice','Sweet warming bark spice.','draft'),
  ('nutmeg','Nutmeg','root-spice','Warm aromatic spice.','draft'),
  ('cardamom','Cardamom','root-spice','Floral aromatic pod spice.','draft'),
  ('cloves','Cloves','root-spice','Pungent warming spice.','draft'),
  ('allspice','Allspice','root-spice','Warm complex berry spice.','draft'),
  ('cayenne','Cayenne','root-spice','Hot ground chili.','draft'),
  ('chili-powder','Chili Powder','root-spice','Blended chili seasoning.','draft'),
  ('red-pepper-flakes','Red Pepper Flakes','root-spice','Dried chili heat.','draft'),
  ('harissa','Harissa','root-spice','North African chili paste.','draft'),
  ('curry-powder','Curry Powder','root-spice','Warm blended spice mix.','draft'),
  ('garam-masala','Garam Masala','root-spice','Aromatic Indian spice blend.','draft'),
  ('oregano','Oregano','root-spice','Robust Mediterranean herb.','draft'),
  ('thyme','Thyme','root-spice','Earthy aromatic herb.','draft'),
  ('rosemary','Rosemary','root-spice','Piney resinous herb.','draft'),
  ('sage','Sage','root-spice','Savory aromatic herb.','draft'),
  ('basil','Basil','root-spice','Sweet fragrant herb.','draft'),
  ('parsley','Parsley','root-spice','Fresh clean-tasting herb.','draft'),
  ('cilantro','Cilantro','root-spice','Bright citrusy herb.','draft'),
  ('mint','Mint','root-spice','Cooling aromatic herb.','draft'),
  ('dill','Dill','root-spice','Grassy aromatic herb.','draft'),
  ('bay-leaves','Bay Leaves','root-spice','Aromatic simmering herb.','draft'),
  ('fennel-seeds','Fennel Seeds','root-spice','Sweet anise-scented seed.','draft'),
  ('mustard-seeds','Mustard Seeds','root-spice','Pungent tiny seed spice.','draft'),
  ('saffron','Saffron','root-spice','Floral golden thread spice.','draft'),
  ('sumac','Sumac','root-spice','Tart ruby-red spice.','draft'),
  ('zaatar','Zaatar','root-spice','Herby sesame spice blend.','draft'),
  ('star-anise','Star Anise','root-spice','Licorice-scented pod spice.','draft'),
  ('fenugreek','Fenugreek','root-spice','Maple-scented seed spice.','draft'),
  ('horseradish','Horseradish','root-spice','Pungent sharp root.','draft'),
  ('lemongrass','Lemongrass','root-spice','Citrusy aromatic stalk.','draft'),
  ('vanilla','Vanilla','root-spice','Sweet aromatic pod.','draft'),
  -- ── Fruits ──────────────────────────────────────────────────────────────
  ('blueberries','Blueberries','fruit','Anthocyanin-rich berry.','draft'),
  ('strawberries','Strawberries','fruit','Vitamin-C rich berry.','draft'),
  ('raspberries','Raspberries','fruit','Fiber-rich tart berry.','draft'),
  ('blackberries','Blackberries','fruit','Antioxidant-rich dark berry.','draft'),
  ('cranberries','Cranberries','fruit','Tart polyphenol-rich berry.','draft'),
  ('lemon','Lemon','fruit','Bright vitamin-C citrus.','draft'),
  ('lime','Lime','fruit','Tangy aromatic citrus.','draft'),
  ('orange','Orange','fruit','Sweet vitamin-C citrus.','draft'),
  ('grapefruit','Grapefruit','fruit','Tart-sweet citrus.','draft'),
  ('apple','Apple','fruit','Fiber-rich everyday fruit.','draft'),
  ('banana','Banana','fruit','Potassium-rich energy fruit.','draft'),
  ('pear','Pear','fruit','Sweet fiber-rich fruit.','draft'),
  ('grapes','Grapes','fruit','Sweet polyphenol-rich fruit.','draft'),
  ('mango','Mango','fruit','Sweet beta-carotene rich tropical fruit.','draft'),
  ('pineapple','Pineapple','fruit','Bromelain-rich tropical fruit.','draft'),
  ('peach','Peach','fruit','Sweet juicy stone fruit.','draft'),
  ('plum','Plum','fruit','Tart-sweet stone fruit.','draft'),
  ('cherries','Cherries','fruit','Anthocyanin-rich stone fruit.','draft'),
  ('pomegranate','Pomegranate','fruit','Punicalagin-rich jeweled fruit.','draft'),
  ('kiwi','Kiwi','fruit','Vitamin-C rich tangy fruit.','draft'),
  ('watermelon','Watermelon','fruit','Hydrating lycopene-rich melon.','draft'),
  ('cantaloupe','Cantaloupe','fruit','Sweet beta-carotene rich melon.','draft'),
  ('dates','Dates','fruit','Fiber-rich natural sweetener fruit.','draft'),
  ('figs','Figs','fruit','Fiber and mineral rich fruit.','draft'),
  ('apricots','Apricots','fruit','Beta-carotene rich stone fruit.','draft'),
  ('raisins','Raisins','fruit','Concentrated dried grapes.','draft'),
  -- ── Ferments ────────────────────────────────────────────────────────────
  ('greek-yogurt','Greek Yogurt','ferments','Strained protein-rich cultured dairy.','draft'),
  ('plain-yogurt','Plain Yogurt','ferments','Probiotic cultured milk.','draft'),
  ('kefir','Kefir','ferments','Probiotic-rich cultured drink.','draft'),
  ('sauerkraut','Sauerkraut','ferments','Fermented cabbage rich in probiotics.','draft'),
  ('kimchi','Kimchi','ferments','Spicy fermented vegetables.','draft'),
  ('miso','Miso','ferments','Fermented soybean paste.','draft'),
  ('kombucha','Kombucha','ferments','Fermented tea with probiotics.','draft'),
  ('natto','Natto','ferments','Fermented soybeans rich in vitamin K2.','draft'),
  ('cottage-cheese','Cottage Cheese','ferments','High-protein fresh cheese.','draft'),
  ('feta-cheese','Feta Cheese','ferments','Briny cultured cheese.','draft'),
  ('parmesan','Parmesan','ferments','Aged umami-rich cheese.','draft'),
  ('pickles','Pickles','ferments','Brined cucumbers.','draft'),
  -- ── Pantry staples ──────────────────────────────────────────────────────
  ('sea-salt','Sea Salt','staple','Mineral-rich seasoning salt.','draft'),
  ('kosher-salt','Kosher Salt','staple','Coarse everyday cooking salt.','draft'),
  ('honey','Honey','staple','Natural sweetener with trace enzymes.','draft'),
  ('maple-syrup','Maple Syrup','staple','Mineral-containing natural sweetener.','draft'),
  ('dijon-mustard','Dijon Mustard','staple','Sharp emulsifying condiment.','draft'),
  ('whole-grain-mustard','Whole Grain Mustard','staple','Textured seeded mustard.','draft'),
  ('apple-cider-vinegar','Apple Cider Vinegar','staple','Tangy fermented vinegar.','draft'),
  ('balsamic-vinegar','Balsamic Vinegar','staple','Sweet-tart aged vinegar.','draft'),
  ('red-wine-vinegar','Red Wine Vinegar','staple','Bright acidic vinegar.','draft'),
  ('rice-vinegar','Rice Vinegar','staple','Mild mellow vinegar.','draft'),
  ('white-wine-vinegar','White Wine Vinegar','staple','Crisp acidic vinegar.','draft'),
  ('soy-sauce','Soy Sauce','staple','Salty umami fermented condiment.','draft'),
  ('tamari','Tamari','staple','Gluten-free soy sauce.','draft'),
  ('fish-sauce','Fish Sauce','staple','Salty umami fermented condiment.','draft'),
  ('coconut-aminos','Coconut Aminos','staple','Soy-free savory sauce.','draft'),
  ('vegetable-broth','Vegetable Broth','staple','Savory cooking base.','draft'),
  ('chicken-broth','Chicken Broth','staple','Savory poultry cooking base.','draft'),
  ('bone-broth','Bone Broth','staple','Collagen-rich simmered stock.','draft'),
  ('tomato-paste','Tomato Paste','staple','Concentrated umami tomato.','draft'),
  ('canned-tomatoes','Canned Tomatoes','staple','Cooking-ready tomatoes.','draft'),
  ('coconut-water','Coconut Water','staple','Electrolyte-rich hydration.','draft'),
  ('cacao-powder','Cacao Powder','staple','Flavanol-rich raw chocolate powder.','draft'),
  ('vanilla-extract','Vanilla Extract','staple','Aromatic baking flavoring.','draft'),
  ('baking-soda','Baking Soda','staple','Leavening agent.','draft'),
  ('arrowroot','Arrowroot','staple','Grain-free thickening starch.','draft'),
  ('cornstarch','Cornstarch','staple','Thickening starch.','draft'),
  ('nori','Nori','staple','Iodine-rich dried seaweed.','draft'),
  -- ── Extras (mapped into the 9-category list) ────────────────────────────
  ('nutritional-yeast','Nutritional Yeast','staple','Cheesy B-vitamin rich flakes.','draft'),
  ('matcha','Matcha','staple','Antioxidant-rich green tea powder.','draft'),
  ('green-tea','Green Tea','staple','Catechin-rich brewed tea.','draft'),
  ('collagen-powder','Collagen Powder','protein','Protein supplement for connective tissue.','draft'),
  ('spirulina','Spirulina','staple','Nutrient-dense blue-green algae.','draft')
on conflict (slug) do nothing;

-- Refresh PostgREST's schema cache so the widened category constraint and the
-- new rows are visible to the API immediately.
notify pgrst, 'reload schema';
